### PR TITLE
Fix as per @macolo comment in #8.

### PR DESCRIPTION
**Pull request by kenorb**
Proposed @macolo fix as per #8, please test.

### CODE REVIEW

**Comment by kenorb** [comment]
@mhawksey Can check and merge it please?

**Comment by mhawksey** [comment]
@kenorb I don't maintain this fork. Suggest committing to https://github.com/fastfedora/google-docs

**Comment by kenorb** [comment]
I did, but the same thing, no update since few months:)

https://github.com/fastfedora/google-docs/pull/18

**Comment by kenorb** [comment]
Merged in upstream (bradjasper/ImportJSON/pull/18).

**Pull request closed without merging**
